version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./www:/var/www/html
      - ./wordpress/wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - 5432

  redis:
    image: redis:alpine
    expose:
      - 6379
    depends_on:
      - wordpress

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./caddy_data:/data
    depends_on:
      - wordpress

volumes:
  wordpress:
  db:
  caddy:
