version: '3.1'
    
  services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db

    web:
      build: .
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/app/
      ports:
        - 8000:8000
      depends_on:
        - db
